apiVersion: v2
name: splunk-synthetics-runner
description: Private location runners for Splunk Synthetic Monitoring
type: application
version: 0.0.15
appVersion: "0.33.0"
keywords:
  - Splunk
  - Observability
  - Synthetic Monitoring
  - Private Location
maintainers:
  - name: Splunk
